apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-eks-cluster
  region: us-west-1

nodeGroups:
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: EKSProjectEC2KeyPair
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator"]
    # All types: ["*"]