kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: development
  name: eks-user-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]  # can be further limited, e.g. ["deployments", "replicasets", "pods"]
  verbs: ["get", "list", "watch"] 