kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: eks-user-binding
  namespace: development
subjects:
- kind: User
  name: eks-user
  apiGroup: ""
roleRef:
  kind: Role
  name: eks-user-role
  apiGroup: ""